[package]
name = "math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1"
serde = { version = "1", features = ["derive"] }
statistics_inference = { git = "https://github.com/Banyc/statistics_inference.git", tag = "v0.0.1" }
strict-num = { version = "0.2", features = ["serde"] }
thiserror = "1"
